# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/rocio/Escritorio/SEGUNDO CUATRIMESTRE 2018/Protocolos de Comunicación/TP PROTOS"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/rocio/Escritorio/SEGUNDO CUATRIMESTRE 2018/Protocolos de Comunicación/TP PROTOS"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/rocio/Escritorio/SEGUNDO CUATRIMESTRE 2018/Protocolos de Comunicación/TP PROTOS/CMakeFiles" "/home/rocio/Escritorio/SEGUNDO CUATRIMESTRE 2018/Protocolos de Comunicación/TP PROTOS/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/rocio/Escritorio/SEGUNDO CUATRIMESTRE 2018/Protocolos de Comunicación/TP PROTOS/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pop3filter

# Build rule for target.
pop3filter: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pop3filter
.PHONY : pop3filter

# fast build rule for target.
pop3filter/fast:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/build
.PHONY : pop3filter/fast

#=============================================================================
# Target rules for targets named pop3ctl

# Build rule for target.
pop3ctl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pop3ctl
.PHONY : pop3ctl

# fast build rule for target.
pop3ctl/fast:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/build
.PHONY : pop3ctl/fast

#=============================================================================
# Target rules for targets named stripmime

# Build rule for target.
stripmime: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 stripmime
.PHONY : stripmime

# fast build rule for target.
stripmime/fast:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/build
.PHONY : stripmime/fast

admin_client/admin.o: admin_client/admin.c.o

.PHONY : admin_client/admin.o

# target to build an object file
admin_client/admin.c.o:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/admin.c.o
.PHONY : admin_client/admin.c.o

admin_client/admin.i: admin_client/admin.c.i

.PHONY : admin_client/admin.i

# target to preprocess a source file
admin_client/admin.c.i:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/admin.c.i
.PHONY : admin_client/admin.c.i

admin_client/admin.s: admin_client/admin.c.s

.PHONY : admin_client/admin.s

# target to generate assembly for a file
admin_client/admin.c.s:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/admin.c.s
.PHONY : admin_client/admin.c.s

admin_client/deserializer.o: admin_client/deserializer.c.o

.PHONY : admin_client/deserializer.o

# target to build an object file
admin_client/deserializer.c.o:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/deserializer.c.o
.PHONY : admin_client/deserializer.c.o

admin_client/deserializer.i: admin_client/deserializer.c.i

.PHONY : admin_client/deserializer.i

# target to preprocess a source file
admin_client/deserializer.c.i:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/deserializer.c.i
.PHONY : admin_client/deserializer.c.i

admin_client/deserializer.s: admin_client/deserializer.c.s

.PHONY : admin_client/deserializer.s

# target to generate assembly for a file
admin_client/deserializer.c.s:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/deserializer.c.s
.PHONY : admin_client/deserializer.c.s

admin_client/input_parser.o: admin_client/input_parser.c.o

.PHONY : admin_client/input_parser.o

# target to build an object file
admin_client/input_parser.c.o:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/input_parser.c.o
.PHONY : admin_client/input_parser.c.o

admin_client/input_parser.i: admin_client/input_parser.c.i

.PHONY : admin_client/input_parser.i

# target to preprocess a source file
admin_client/input_parser.c.i:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/input_parser.c.i
.PHONY : admin_client/input_parser.c.i

admin_client/input_parser.s: admin_client/input_parser.c.s

.PHONY : admin_client/input_parser.s

# target to generate assembly for a file
admin_client/input_parser.c.s:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/input_parser.c.s
.PHONY : admin_client/input_parser.c.s

admin_client/main.o: admin_client/main.c.o

.PHONY : admin_client/main.o

# target to build an object file
admin_client/main.c.o:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/main.c.o
.PHONY : admin_client/main.c.o

admin_client/main.i: admin_client/main.c.i

.PHONY : admin_client/main.i

# target to preprocess a source file
admin_client/main.c.i:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/main.c.i
.PHONY : admin_client/main.c.i

admin_client/main.s: admin_client/main.c.s

.PHONY : admin_client/main.s

# target to generate assembly for a file
admin_client/main.c.s:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/main.c.s
.PHONY : admin_client/main.c.s

admin_client/receive_response.o: admin_client/receive_response.c.o

.PHONY : admin_client/receive_response.o

# target to build an object file
admin_client/receive_response.c.o:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/receive_response.c.o
.PHONY : admin_client/receive_response.c.o

admin_client/receive_response.i: admin_client/receive_response.c.i

.PHONY : admin_client/receive_response.i

# target to preprocess a source file
admin_client/receive_response.c.i:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/receive_response.c.i
.PHONY : admin_client/receive_response.c.i

admin_client/receive_response.s: admin_client/receive_response.c.s

.PHONY : admin_client/receive_response.s

# target to generate assembly for a file
admin_client/receive_response.c.s:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/receive_response.c.s
.PHONY : admin_client/receive_response.c.s

admin_client/send_request.o: admin_client/send_request.c.o

.PHONY : admin_client/send_request.o

# target to build an object file
admin_client/send_request.c.o:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/send_request.c.o
.PHONY : admin_client/send_request.c.o

admin_client/send_request.i: admin_client/send_request.c.i

.PHONY : admin_client/send_request.i

# target to preprocess a source file
admin_client/send_request.c.i:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/send_request.c.i
.PHONY : admin_client/send_request.c.i

admin_client/send_request.s: admin_client/send_request.c.s

.PHONY : admin_client/send_request.s

# target to generate assembly for a file
admin_client/send_request.c.s:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/send_request.c.s
.PHONY : admin_client/send_request.c.s

admin_client/serializer.o: admin_client/serializer.c.o

.PHONY : admin_client/serializer.o

# target to build an object file
admin_client/serializer.c.o:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/serializer.c.o
.PHONY : admin_client/serializer.c.o

admin_client/serializer.i: admin_client/serializer.c.i

.PHONY : admin_client/serializer.i

# target to preprocess a source file
admin_client/serializer.c.i:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/serializer.c.i
.PHONY : admin_client/serializer.c.i

admin_client/serializer.s: admin_client/serializer.c.s

.PHONY : admin_client/serializer.s

# target to generate assembly for a file
admin_client/serializer.c.s:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/serializer.c.s
.PHONY : admin_client/serializer.c.s

admin_client/utils.o: admin_client/utils.c.o

.PHONY : admin_client/utils.o

# target to build an object file
admin_client/utils.c.o:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/utils.c.o
.PHONY : admin_client/utils.c.o

admin_client/utils.i: admin_client/utils.c.i

.PHONY : admin_client/utils.i

# target to preprocess a source file
admin_client/utils.c.i:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/utils.c.i
.PHONY : admin_client/utils.c.i

admin_client/utils.s: admin_client/utils.c.s

.PHONY : admin_client/utils.s

# target to generate assembly for a file
admin_client/utils.c.s:
	$(MAKE) -f CMakeFiles/pop3ctl.dir/build.make CMakeFiles/pop3ctl.dir/admin_client/utils.c.s
.PHONY : admin_client/utils.c.s

mime_filter/delimiter.o: mime_filter/delimiter.c.o

.PHONY : mime_filter/delimiter.o

# target to build an object file
mime_filter/delimiter.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/delimiter.c.o
.PHONY : mime_filter/delimiter.c.o

mime_filter/delimiter.i: mime_filter/delimiter.c.i

.PHONY : mime_filter/delimiter.i

# target to preprocess a source file
mime_filter/delimiter.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/delimiter.c.i
.PHONY : mime_filter/delimiter.c.i

mime_filter/delimiter.s: mime_filter/delimiter.c.s

.PHONY : mime_filter/delimiter.s

# target to generate assembly for a file
mime_filter/delimiter.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/delimiter.c.s
.PHONY : mime_filter/delimiter.c.s

mime_filter/mime_chars.o: mime_filter/mime_chars.c.o

.PHONY : mime_filter/mime_chars.o

# target to build an object file
mime_filter/mime_chars.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_chars.c.o
.PHONY : mime_filter/mime_chars.c.o

mime_filter/mime_chars.i: mime_filter/mime_chars.c.i

.PHONY : mime_filter/mime_chars.i

# target to preprocess a source file
mime_filter/mime_chars.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_chars.c.i
.PHONY : mime_filter/mime_chars.c.i

mime_filter/mime_chars.s: mime_filter/mime_chars.c.s

.PHONY : mime_filter/mime_chars.s

# target to generate assembly for a file
mime_filter/mime_chars.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_chars.c.s
.PHONY : mime_filter/mime_chars.c.s

mime_filter/mime_filter.o: mime_filter/mime_filter.c.o

.PHONY : mime_filter/mime_filter.o

# target to build an object file
mime_filter/mime_filter.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_filter.c.o
.PHONY : mime_filter/mime_filter.c.o

mime_filter/mime_filter.i: mime_filter/mime_filter.c.i

.PHONY : mime_filter/mime_filter.i

# target to preprocess a source file
mime_filter/mime_filter.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_filter.c.i
.PHONY : mime_filter/mime_filter.c.i

mime_filter/mime_filter.s: mime_filter/mime_filter.c.s

.PHONY : mime_filter/mime_filter.s

# target to generate assembly for a file
mime_filter/mime_filter.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_filter.c.s
.PHONY : mime_filter/mime_filter.c.s

mime_filter/mime_list.o: mime_filter/mime_list.c.o

.PHONY : mime_filter/mime_list.o

# target to build an object file
mime_filter/mime_list.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_list.c.o
.PHONY : mime_filter/mime_list.c.o

mime_filter/mime_list.i: mime_filter/mime_list.c.i

.PHONY : mime_filter/mime_list.i

# target to preprocess a source file
mime_filter/mime_list.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_list.c.i
.PHONY : mime_filter/mime_list.c.i

mime_filter/mime_list.s: mime_filter/mime_list.c.s

.PHONY : mime_filter/mime_list.s

# target to generate assembly for a file
mime_filter/mime_list.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_list.c.s
.PHONY : mime_filter/mime_list.c.s

mime_filter/mime_msg.o: mime_filter/mime_msg.c.o

.PHONY : mime_filter/mime_msg.o

# target to build an object file
mime_filter/mime_msg.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_msg.c.o
.PHONY : mime_filter/mime_msg.c.o

mime_filter/mime_msg.i: mime_filter/mime_msg.c.i

.PHONY : mime_filter/mime_msg.i

# target to preprocess a source file
mime_filter/mime_msg.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_msg.c.i
.PHONY : mime_filter/mime_msg.c.i

mime_filter/mime_msg.s: mime_filter/mime_msg.c.s

.PHONY : mime_filter/mime_msg.s

# target to generate assembly for a file
mime_filter/mime_msg.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_msg.c.s
.PHONY : mime_filter/mime_msg.c.s

mime_filter/mime_type.o: mime_filter/mime_type.c.o

.PHONY : mime_filter/mime_type.o

# target to build an object file
mime_filter/mime_type.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_type.c.o
.PHONY : mime_filter/mime_type.c.o

mime_filter/mime_type.i: mime_filter/mime_type.c.i

.PHONY : mime_filter/mime_type.i

# target to preprocess a source file
mime_filter/mime_type.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_type.c.i
.PHONY : mime_filter/mime_type.c.i

mime_filter/mime_type.s: mime_filter/mime_type.c.s

.PHONY : mime_filter/mime_type.s

# target to generate assembly for a file
mime_filter/mime_type.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/mime_type.c.s
.PHONY : mime_filter/mime_type.c.s

mime_filter/multi_pop3_parser.o: mime_filter/multi_pop3_parser.c.o

.PHONY : mime_filter/multi_pop3_parser.o

# target to build an object file
mime_filter/multi_pop3_parser.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/multi_pop3_parser.c.o
.PHONY : mime_filter/multi_pop3_parser.c.o

mime_filter/multi_pop3_parser.i: mime_filter/multi_pop3_parser.c.i

.PHONY : mime_filter/multi_pop3_parser.i

# target to preprocess a source file
mime_filter/multi_pop3_parser.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/multi_pop3_parser.c.i
.PHONY : mime_filter/multi_pop3_parser.c.i

mime_filter/multi_pop3_parser.s: mime_filter/multi_pop3_parser.c.s

.PHONY : mime_filter/multi_pop3_parser.s

# target to generate assembly for a file
mime_filter/multi_pop3_parser.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/multi_pop3_parser.c.s
.PHONY : mime_filter/multi_pop3_parser.c.s

mime_filter/parser_creator.o: mime_filter/parser_creator.c.o

.PHONY : mime_filter/parser_creator.o

# target to build an object file
mime_filter/parser_creator.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/parser_creator.c.o
.PHONY : mime_filter/parser_creator.c.o

mime_filter/parser_creator.i: mime_filter/parser_creator.c.i

.PHONY : mime_filter/parser_creator.i

# target to preprocess a source file
mime_filter/parser_creator.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/parser_creator.c.i
.PHONY : mime_filter/parser_creator.c.i

mime_filter/parser_creator.s: mime_filter/parser_creator.c.s

.PHONY : mime_filter/parser_creator.s

# target to generate assembly for a file
mime_filter/parser_creator.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/parser_creator.c.s
.PHONY : mime_filter/parser_creator.c.s

mime_filter/parser_utils.o: mime_filter/parser_utils.c.o

.PHONY : mime_filter/parser_utils.o

# target to build an object file
mime_filter/parser_utils.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/parser_utils.c.o
.PHONY : mime_filter/parser_utils.c.o

mime_filter/parser_utils.i: mime_filter/parser_utils.c.i

.PHONY : mime_filter/parser_utils.i

# target to preprocess a source file
mime_filter/parser_utils.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/parser_utils.c.i
.PHONY : mime_filter/parser_utils.c.i

mime_filter/parser_utils.s: mime_filter/parser_utils.c.s

.PHONY : mime_filter/parser_utils.s

# target to generate assembly for a file
mime_filter/parser_utils.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/parser_utils.c.s
.PHONY : mime_filter/parser_utils.c.s

mime_filter/stack.o: mime_filter/stack.c.o

.PHONY : mime_filter/stack.o

# target to build an object file
mime_filter/stack.c.o:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/stack.c.o
.PHONY : mime_filter/stack.c.o

mime_filter/stack.i: mime_filter/stack.c.i

.PHONY : mime_filter/stack.i

# target to preprocess a source file
mime_filter/stack.c.i:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/stack.c.i
.PHONY : mime_filter/stack.c.i

mime_filter/stack.s: mime_filter/stack.c.s

.PHONY : mime_filter/stack.s

# target to generate assembly for a file
mime_filter/stack.c.s:
	$(MAKE) -f CMakeFiles/stripmime.dir/build.make CMakeFiles/stripmime.dir/mime_filter/stack.c.s
.PHONY : mime_filter/stack.c.s

proxy_pop3/admin.o: proxy_pop3/admin.c.o

.PHONY : proxy_pop3/admin.o

# target to build an object file
proxy_pop3/admin.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin.c.o
.PHONY : proxy_pop3/admin.c.o

proxy_pop3/admin.i: proxy_pop3/admin.c.i

.PHONY : proxy_pop3/admin.i

# target to preprocess a source file
proxy_pop3/admin.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin.c.i
.PHONY : proxy_pop3/admin.c.i

proxy_pop3/admin.s: proxy_pop3/admin.c.s

.PHONY : proxy_pop3/admin.s

# target to generate assembly for a file
proxy_pop3/admin.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin.c.s
.PHONY : proxy_pop3/admin.c.s

proxy_pop3/admin_actions.o: proxy_pop3/admin_actions.c.o

.PHONY : proxy_pop3/admin_actions.o

# target to build an object file
proxy_pop3/admin_actions.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_actions.c.o
.PHONY : proxy_pop3/admin_actions.c.o

proxy_pop3/admin_actions.i: proxy_pop3/admin_actions.c.i

.PHONY : proxy_pop3/admin_actions.i

# target to preprocess a source file
proxy_pop3/admin_actions.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_actions.c.i
.PHONY : proxy_pop3/admin_actions.c.i

proxy_pop3/admin_actions.s: proxy_pop3/admin_actions.c.s

.PHONY : proxy_pop3/admin_actions.s

# target to generate assembly for a file
proxy_pop3/admin_actions.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_actions.c.s
.PHONY : proxy_pop3/admin_actions.c.s

proxy_pop3/admin_deserializer.o: proxy_pop3/admin_deserializer.c.o

.PHONY : proxy_pop3/admin_deserializer.o

# target to build an object file
proxy_pop3/admin_deserializer.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_deserializer.c.o
.PHONY : proxy_pop3/admin_deserializer.c.o

proxy_pop3/admin_deserializer.i: proxy_pop3/admin_deserializer.c.i

.PHONY : proxy_pop3/admin_deserializer.i

# target to preprocess a source file
proxy_pop3/admin_deserializer.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_deserializer.c.i
.PHONY : proxy_pop3/admin_deserializer.c.i

proxy_pop3/admin_deserializer.s: proxy_pop3/admin_deserializer.c.s

.PHONY : proxy_pop3/admin_deserializer.s

# target to generate assembly for a file
proxy_pop3/admin_deserializer.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_deserializer.c.s
.PHONY : proxy_pop3/admin_deserializer.c.s

proxy_pop3/admin_parse_response.o: proxy_pop3/admin_parse_response.c.o

.PHONY : proxy_pop3/admin_parse_response.o

# target to build an object file
proxy_pop3/admin_parse_response.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_parse_response.c.o
.PHONY : proxy_pop3/admin_parse_response.c.o

proxy_pop3/admin_parse_response.i: proxy_pop3/admin_parse_response.c.i

.PHONY : proxy_pop3/admin_parse_response.i

# target to preprocess a source file
proxy_pop3/admin_parse_response.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_parse_response.c.i
.PHONY : proxy_pop3/admin_parse_response.c.i

proxy_pop3/admin_parse_response.s: proxy_pop3/admin_parse_response.c.s

.PHONY : proxy_pop3/admin_parse_response.s

# target to generate assembly for a file
proxy_pop3/admin_parse_response.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_parse_response.c.s
.PHONY : proxy_pop3/admin_parse_response.c.s

proxy_pop3/admin_parser_request.o: proxy_pop3/admin_parser_request.c.o

.PHONY : proxy_pop3/admin_parser_request.o

# target to build an object file
proxy_pop3/admin_parser_request.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_parser_request.c.o
.PHONY : proxy_pop3/admin_parser_request.c.o

proxy_pop3/admin_parser_request.i: proxy_pop3/admin_parser_request.c.i

.PHONY : proxy_pop3/admin_parser_request.i

# target to preprocess a source file
proxy_pop3/admin_parser_request.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_parser_request.c.i
.PHONY : proxy_pop3/admin_parser_request.c.i

proxy_pop3/admin_parser_request.s: proxy_pop3/admin_parser_request.c.s

.PHONY : proxy_pop3/admin_parser_request.s

# target to generate assembly for a file
proxy_pop3/admin_parser_request.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_parser_request.c.s
.PHONY : proxy_pop3/admin_parser_request.c.s

proxy_pop3/admin_serializer.o: proxy_pop3/admin_serializer.c.o

.PHONY : proxy_pop3/admin_serializer.o

# target to build an object file
proxy_pop3/admin_serializer.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_serializer.c.o
.PHONY : proxy_pop3/admin_serializer.c.o

proxy_pop3/admin_serializer.i: proxy_pop3/admin_serializer.c.i

.PHONY : proxy_pop3/admin_serializer.i

# target to preprocess a source file
proxy_pop3/admin_serializer.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_serializer.c.i
.PHONY : proxy_pop3/admin_serializer.c.i

proxy_pop3/admin_serializer.s: proxy_pop3/admin_serializer.c.s

.PHONY : proxy_pop3/admin_serializer.s

# target to generate assembly for a file
proxy_pop3/admin_serializer.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/admin_serializer.c.s
.PHONY : proxy_pop3/admin_serializer.c.s

proxy_pop3/buffer.o: proxy_pop3/buffer.c.o

.PHONY : proxy_pop3/buffer.o

# target to build an object file
proxy_pop3/buffer.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/buffer.c.o
.PHONY : proxy_pop3/buffer.c.o

proxy_pop3/buffer.i: proxy_pop3/buffer.c.i

.PHONY : proxy_pop3/buffer.i

# target to preprocess a source file
proxy_pop3/buffer.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/buffer.c.i
.PHONY : proxy_pop3/buffer.c.i

proxy_pop3/buffer.s: proxy_pop3/buffer.c.s

.PHONY : proxy_pop3/buffer.s

# target to generate assembly for a file
proxy_pop3/buffer.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/buffer.c.s
.PHONY : proxy_pop3/buffer.c.s

proxy_pop3/client_parser_request.o: proxy_pop3/client_parser_request.c.o

.PHONY : proxy_pop3/client_parser_request.o

# target to build an object file
proxy_pop3/client_parser_request.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_parser_request.c.o
.PHONY : proxy_pop3/client_parser_request.c.o

proxy_pop3/client_parser_request.i: proxy_pop3/client_parser_request.c.i

.PHONY : proxy_pop3/client_parser_request.i

# target to preprocess a source file
proxy_pop3/client_parser_request.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_parser_request.c.i
.PHONY : proxy_pop3/client_parser_request.c.i

proxy_pop3/client_parser_request.s: proxy_pop3/client_parser_request.c.s

.PHONY : proxy_pop3/client_parser_request.s

# target to generate assembly for a file
proxy_pop3/client_parser_request.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_parser_request.c.s
.PHONY : proxy_pop3/client_parser_request.c.s

proxy_pop3/client_parser_response.o: proxy_pop3/client_parser_response.c.o

.PHONY : proxy_pop3/client_parser_response.o

# target to build an object file
proxy_pop3/client_parser_response.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_parser_response.c.o
.PHONY : proxy_pop3/client_parser_response.c.o

proxy_pop3/client_parser_response.i: proxy_pop3/client_parser_response.c.i

.PHONY : proxy_pop3/client_parser_response.i

# target to preprocess a source file
proxy_pop3/client_parser_response.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_parser_response.c.i
.PHONY : proxy_pop3/client_parser_response.c.i

proxy_pop3/client_parser_response.s: proxy_pop3/client_parser_response.c.s

.PHONY : proxy_pop3/client_parser_response.s

# target to generate assembly for a file
proxy_pop3/client_parser_response.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_parser_response.c.s
.PHONY : proxy_pop3/client_parser_response.c.s

proxy_pop3/client_request.o: proxy_pop3/client_request.c.o

.PHONY : proxy_pop3/client_request.o

# target to build an object file
proxy_pop3/client_request.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_request.c.o
.PHONY : proxy_pop3/client_request.c.o

proxy_pop3/client_request.i: proxy_pop3/client_request.c.i

.PHONY : proxy_pop3/client_request.i

# target to preprocess a source file
proxy_pop3/client_request.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_request.c.i
.PHONY : proxy_pop3/client_request.c.i

proxy_pop3/client_request.s: proxy_pop3/client_request.c.s

.PHONY : proxy_pop3/client_request.s

# target to generate assembly for a file
proxy_pop3/client_request.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_request.c.s
.PHONY : proxy_pop3/client_request.c.s

proxy_pop3/client_request_utils.o: proxy_pop3/client_request_utils.c.o

.PHONY : proxy_pop3/client_request_utils.o

# target to build an object file
proxy_pop3/client_request_utils.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_request_utils.c.o
.PHONY : proxy_pop3/client_request_utils.c.o

proxy_pop3/client_request_utils.i: proxy_pop3/client_request_utils.c.i

.PHONY : proxy_pop3/client_request_utils.i

# target to preprocess a source file
proxy_pop3/client_request_utils.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_request_utils.c.i
.PHONY : proxy_pop3/client_request_utils.c.i

proxy_pop3/client_request_utils.s: proxy_pop3/client_request_utils.c.s

.PHONY : proxy_pop3/client_request_utils.s

# target to generate assembly for a file
proxy_pop3/client_request_utils.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_request_utils.c.s
.PHONY : proxy_pop3/client_request_utils.c.s

proxy_pop3/client_response.o: proxy_pop3/client_response.c.o

.PHONY : proxy_pop3/client_response.o

# target to build an object file
proxy_pop3/client_response.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_response.c.o
.PHONY : proxy_pop3/client_response.c.o

proxy_pop3/client_response.i: proxy_pop3/client_response.c.i

.PHONY : proxy_pop3/client_response.i

# target to preprocess a source file
proxy_pop3/client_response.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_response.c.i
.PHONY : proxy_pop3/client_response.c.i

proxy_pop3/client_response.s: proxy_pop3/client_response.c.s

.PHONY : proxy_pop3/client_response.s

# target to generate assembly for a file
proxy_pop3/client_response.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_response.c.s
.PHONY : proxy_pop3/client_response.c.s

proxy_pop3/client_response_utils.o: proxy_pop3/client_response_utils.c.o

.PHONY : proxy_pop3/client_response_utils.o

# target to build an object file
proxy_pop3/client_response_utils.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_response_utils.c.o
.PHONY : proxy_pop3/client_response_utils.c.o

proxy_pop3/client_response_utils.i: proxy_pop3/client_response_utils.c.i

.PHONY : proxy_pop3/client_response_utils.i

# target to preprocess a source file
proxy_pop3/client_response_utils.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_response_utils.c.i
.PHONY : proxy_pop3/client_response_utils.c.i

proxy_pop3/client_response_utils.s: proxy_pop3/client_response_utils.c.s

.PHONY : proxy_pop3/client_response_utils.s

# target to generate assembly for a file
proxy_pop3/client_response_utils.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/client_response_utils.c.s
.PHONY : proxy_pop3/client_response_utils.c.s

proxy_pop3/external_transformation.o: proxy_pop3/external_transformation.c.o

.PHONY : proxy_pop3/external_transformation.o

# target to build an object file
proxy_pop3/external_transformation.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/external_transformation.c.o
.PHONY : proxy_pop3/external_transformation.c.o

proxy_pop3/external_transformation.i: proxy_pop3/external_transformation.c.i

.PHONY : proxy_pop3/external_transformation.i

# target to preprocess a source file
proxy_pop3/external_transformation.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/external_transformation.c.i
.PHONY : proxy_pop3/external_transformation.c.i

proxy_pop3/external_transformation.s: proxy_pop3/external_transformation.c.s

.PHONY : proxy_pop3/external_transformation.s

# target to generate assembly for a file
proxy_pop3/external_transformation.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/external_transformation.c.s
.PHONY : proxy_pop3/external_transformation.c.s

proxy_pop3/filter_list.o: proxy_pop3/filter_list.c.o

.PHONY : proxy_pop3/filter_list.o

# target to build an object file
proxy_pop3/filter_list.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/filter_list.c.o
.PHONY : proxy_pop3/filter_list.c.o

proxy_pop3/filter_list.i: proxy_pop3/filter_list.c.i

.PHONY : proxy_pop3/filter_list.i

# target to preprocess a source file
proxy_pop3/filter_list.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/filter_list.c.i
.PHONY : proxy_pop3/filter_list.c.i

proxy_pop3/filter_list.s: proxy_pop3/filter_list.c.s

.PHONY : proxy_pop3/filter_list.s

# target to generate assembly for a file
proxy_pop3/filter_list.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/filter_list.c.s
.PHONY : proxy_pop3/filter_list.c.s

proxy_pop3/input_parser.o: proxy_pop3/input_parser.c.o

.PHONY : proxy_pop3/input_parser.o

# target to build an object file
proxy_pop3/input_parser.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/input_parser.c.o
.PHONY : proxy_pop3/input_parser.c.o

proxy_pop3/input_parser.i: proxy_pop3/input_parser.c.i

.PHONY : proxy_pop3/input_parser.i

# target to preprocess a source file
proxy_pop3/input_parser.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/input_parser.c.i
.PHONY : proxy_pop3/input_parser.c.i

proxy_pop3/input_parser.s: proxy_pop3/input_parser.c.s

.PHONY : proxy_pop3/input_parser.s

# target to generate assembly for a file
proxy_pop3/input_parser.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/input_parser.c.s
.PHONY : proxy_pop3/input_parser.c.s

proxy_pop3/logs.o: proxy_pop3/logs.c.o

.PHONY : proxy_pop3/logs.o

# target to build an object file
proxy_pop3/logs.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/logs.c.o
.PHONY : proxy_pop3/logs.c.o

proxy_pop3/logs.i: proxy_pop3/logs.c.i

.PHONY : proxy_pop3/logs.i

# target to preprocess a source file
proxy_pop3/logs.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/logs.c.i
.PHONY : proxy_pop3/logs.c.i

proxy_pop3/logs.s: proxy_pop3/logs.c.s

.PHONY : proxy_pop3/logs.s

# target to generate assembly for a file
proxy_pop3/logs.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/logs.c.s
.PHONY : proxy_pop3/logs.c.s

proxy_pop3/main.o: proxy_pop3/main.c.o

.PHONY : proxy_pop3/main.o

# target to build an object file
proxy_pop3/main.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/main.c.o
.PHONY : proxy_pop3/main.c.o

proxy_pop3/main.i: proxy_pop3/main.c.i

.PHONY : proxy_pop3/main.i

# target to preprocess a source file
proxy_pop3/main.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/main.c.i
.PHONY : proxy_pop3/main.c.i

proxy_pop3/main.s: proxy_pop3/main.c.s

.PHONY : proxy_pop3/main.s

# target to generate assembly for a file
proxy_pop3/main.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/main.c.s
.PHONY : proxy_pop3/main.c.s

proxy_pop3/metrics.o: proxy_pop3/metrics.c.o

.PHONY : proxy_pop3/metrics.o

# target to build an object file
proxy_pop3/metrics.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/metrics.c.o
.PHONY : proxy_pop3/metrics.c.o

proxy_pop3/metrics.i: proxy_pop3/metrics.c.i

.PHONY : proxy_pop3/metrics.i

# target to preprocess a source file
proxy_pop3/metrics.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/metrics.c.i
.PHONY : proxy_pop3/metrics.c.i

proxy_pop3/metrics.s: proxy_pop3/metrics.c.s

.PHONY : proxy_pop3/metrics.s

# target to generate assembly for a file
proxy_pop3/metrics.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/metrics.c.s
.PHONY : proxy_pop3/metrics.c.s

proxy_pop3/msg_queue.o: proxy_pop3/msg_queue.c.o

.PHONY : proxy_pop3/msg_queue.o

# target to build an object file
proxy_pop3/msg_queue.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/msg_queue.c.o
.PHONY : proxy_pop3/msg_queue.c.o

proxy_pop3/msg_queue.i: proxy_pop3/msg_queue.c.i

.PHONY : proxy_pop3/msg_queue.i

# target to preprocess a source file
proxy_pop3/msg_queue.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/msg_queue.c.i
.PHONY : proxy_pop3/msg_queue.c.i

proxy_pop3/msg_queue.s: proxy_pop3/msg_queue.c.s

.PHONY : proxy_pop3/msg_queue.s

# target to generate assembly for a file
proxy_pop3/msg_queue.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/msg_queue.c.s
.PHONY : proxy_pop3/msg_queue.c.s

proxy_pop3/parser.o: proxy_pop3/parser.c.o

.PHONY : proxy_pop3/parser.o

# target to build an object file
proxy_pop3/parser.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/parser.c.o
.PHONY : proxy_pop3/parser.c.o

proxy_pop3/parser.i: proxy_pop3/parser.c.i

.PHONY : proxy_pop3/parser.i

# target to preprocess a source file
proxy_pop3/parser.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/parser.c.i
.PHONY : proxy_pop3/parser.c.i

proxy_pop3/parser.s: proxy_pop3/parser.c.s

.PHONY : proxy_pop3/parser.s

# target to generate assembly for a file
proxy_pop3/parser.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/parser.c.s
.PHONY : proxy_pop3/parser.c.s

proxy_pop3/pipelining.o: proxy_pop3/pipelining.c.o

.PHONY : proxy_pop3/pipelining.o

# target to build an object file
proxy_pop3/pipelining.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pipelining.c.o
.PHONY : proxy_pop3/pipelining.c.o

proxy_pop3/pipelining.i: proxy_pop3/pipelining.c.i

.PHONY : proxy_pop3/pipelining.i

# target to preprocess a source file
proxy_pop3/pipelining.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pipelining.c.i
.PHONY : proxy_pop3/pipelining.c.i

proxy_pop3/pipelining.s: proxy_pop3/pipelining.c.s

.PHONY : proxy_pop3/pipelining.s

# target to generate assembly for a file
proxy_pop3/pipelining.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pipelining.c.s
.PHONY : proxy_pop3/pipelining.c.s

proxy_pop3/pop3_handler.o: proxy_pop3/pop3_handler.c.o

.PHONY : proxy_pop3/pop3_handler.o

# target to build an object file
proxy_pop3/pop3_handler.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3_handler.c.o
.PHONY : proxy_pop3/pop3_handler.c.o

proxy_pop3/pop3_handler.i: proxy_pop3/pop3_handler.c.i

.PHONY : proxy_pop3/pop3_handler.i

# target to preprocess a source file
proxy_pop3/pop3_handler.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3_handler.c.i
.PHONY : proxy_pop3/pop3_handler.c.i

proxy_pop3/pop3_handler.s: proxy_pop3/pop3_handler.c.s

.PHONY : proxy_pop3/pop3_handler.s

# target to generate assembly for a file
proxy_pop3/pop3_handler.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3_handler.c.s
.PHONY : proxy_pop3/pop3_handler.c.s

proxy_pop3/pop3_multi.o: proxy_pop3/pop3_multi.c.o

.PHONY : proxy_pop3/pop3_multi.o

# target to build an object file
proxy_pop3/pop3_multi.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3_multi.c.o
.PHONY : proxy_pop3/pop3_multi.c.o

proxy_pop3/pop3_multi.i: proxy_pop3/pop3_multi.c.i

.PHONY : proxy_pop3/pop3_multi.i

# target to preprocess a source file
proxy_pop3/pop3_multi.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3_multi.c.i
.PHONY : proxy_pop3/pop3_multi.c.i

proxy_pop3/pop3_multi.s: proxy_pop3/pop3_multi.c.s

.PHONY : proxy_pop3/pop3_multi.s

# target to generate assembly for a file
proxy_pop3/pop3_multi.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3_multi.c.s
.PHONY : proxy_pop3/pop3_multi.c.s

proxy_pop3/pop3_session.o: proxy_pop3/pop3_session.c.o

.PHONY : proxy_pop3/pop3_session.o

# target to build an object file
proxy_pop3/pop3_session.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3_session.c.o
.PHONY : proxy_pop3/pop3_session.c.o

proxy_pop3/pop3_session.i: proxy_pop3/pop3_session.c.i

.PHONY : proxy_pop3/pop3_session.i

# target to preprocess a source file
proxy_pop3/pop3_session.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3_session.c.i
.PHONY : proxy_pop3/pop3_session.c.i

proxy_pop3/pop3_session.s: proxy_pop3/pop3_session.c.s

.PHONY : proxy_pop3/pop3_session.s

# target to generate assembly for a file
proxy_pop3/pop3_session.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3_session.c.s
.PHONY : proxy_pop3/pop3_session.c.s

proxy_pop3/pop3nio.o: proxy_pop3/pop3nio.c.o

.PHONY : proxy_pop3/pop3nio.o

# target to build an object file
proxy_pop3/pop3nio.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3nio.c.o
.PHONY : proxy_pop3/pop3nio.c.o

proxy_pop3/pop3nio.i: proxy_pop3/pop3nio.c.i

.PHONY : proxy_pop3/pop3nio.i

# target to preprocess a source file
proxy_pop3/pop3nio.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3nio.c.i
.PHONY : proxy_pop3/pop3nio.c.i

proxy_pop3/pop3nio.s: proxy_pop3/pop3nio.c.s

.PHONY : proxy_pop3/pop3nio.s

# target to generate assembly for a file
proxy_pop3/pop3nio.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/pop3nio.c.s
.PHONY : proxy_pop3/pop3nio.c.s

proxy_pop3/selector.o: proxy_pop3/selector.c.o

.PHONY : proxy_pop3/selector.o

# target to build an object file
proxy_pop3/selector.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/selector.c.o
.PHONY : proxy_pop3/selector.c.o

proxy_pop3/selector.i: proxy_pop3/selector.c.i

.PHONY : proxy_pop3/selector.i

# target to preprocess a source file
proxy_pop3/selector.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/selector.c.i
.PHONY : proxy_pop3/selector.c.i

proxy_pop3/selector.s: proxy_pop3/selector.c.s

.PHONY : proxy_pop3/selector.s

# target to generate assembly for a file
proxy_pop3/selector.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/selector.c.s
.PHONY : proxy_pop3/selector.c.s

proxy_pop3/stm.o: proxy_pop3/stm.c.o

.PHONY : proxy_pop3/stm.o

# target to build an object file
proxy_pop3/stm.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/stm.c.o
.PHONY : proxy_pop3/stm.c.o

proxy_pop3/stm.i: proxy_pop3/stm.c.i

.PHONY : proxy_pop3/stm.i

# target to preprocess a source file
proxy_pop3/stm.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/stm.c.i
.PHONY : proxy_pop3/stm.c.i

proxy_pop3/stm.s: proxy_pop3/stm.c.s

.PHONY : proxy_pop3/stm.s

# target to generate assembly for a file
proxy_pop3/stm.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/stm.c.s
.PHONY : proxy_pop3/stm.c.s

proxy_pop3/utils.o: proxy_pop3/utils.c.o

.PHONY : proxy_pop3/utils.o

# target to build an object file
proxy_pop3/utils.c.o:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/utils.c.o
.PHONY : proxy_pop3/utils.c.o

proxy_pop3/utils.i: proxy_pop3/utils.c.i

.PHONY : proxy_pop3/utils.i

# target to preprocess a source file
proxy_pop3/utils.c.i:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/utils.c.i
.PHONY : proxy_pop3/utils.c.i

proxy_pop3/utils.s: proxy_pop3/utils.c.s

.PHONY : proxy_pop3/utils.s

# target to generate assembly for a file
proxy_pop3/utils.c.s:
	$(MAKE) -f CMakeFiles/pop3filter.dir/build.make CMakeFiles/pop3filter.dir/proxy_pop3/utils.c.s
.PHONY : proxy_pop3/utils.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... pop3filter"
	@echo "... pop3ctl"
	@echo "... rebuild_cache"
	@echo "... stripmime"
	@echo "... admin_client/admin.o"
	@echo "... admin_client/admin.i"
	@echo "... admin_client/admin.s"
	@echo "... admin_client/deserializer.o"
	@echo "... admin_client/deserializer.i"
	@echo "... admin_client/deserializer.s"
	@echo "... admin_client/input_parser.o"
	@echo "... admin_client/input_parser.i"
	@echo "... admin_client/input_parser.s"
	@echo "... admin_client/main.o"
	@echo "... admin_client/main.i"
	@echo "... admin_client/main.s"
	@echo "... admin_client/receive_response.o"
	@echo "... admin_client/receive_response.i"
	@echo "... admin_client/receive_response.s"
	@echo "... admin_client/send_request.o"
	@echo "... admin_client/send_request.i"
	@echo "... admin_client/send_request.s"
	@echo "... admin_client/serializer.o"
	@echo "... admin_client/serializer.i"
	@echo "... admin_client/serializer.s"
	@echo "... admin_client/utils.o"
	@echo "... admin_client/utils.i"
	@echo "... admin_client/utils.s"
	@echo "... mime_filter/delimiter.o"
	@echo "... mime_filter/delimiter.i"
	@echo "... mime_filter/delimiter.s"
	@echo "... mime_filter/mime_chars.o"
	@echo "... mime_filter/mime_chars.i"
	@echo "... mime_filter/mime_chars.s"
	@echo "... mime_filter/mime_filter.o"
	@echo "... mime_filter/mime_filter.i"
	@echo "... mime_filter/mime_filter.s"
	@echo "... mime_filter/mime_list.o"
	@echo "... mime_filter/mime_list.i"
	@echo "... mime_filter/mime_list.s"
	@echo "... mime_filter/mime_msg.o"
	@echo "... mime_filter/mime_msg.i"
	@echo "... mime_filter/mime_msg.s"
	@echo "... mime_filter/mime_type.o"
	@echo "... mime_filter/mime_type.i"
	@echo "... mime_filter/mime_type.s"
	@echo "... mime_filter/multi_pop3_parser.o"
	@echo "... mime_filter/multi_pop3_parser.i"
	@echo "... mime_filter/multi_pop3_parser.s"
	@echo "... mime_filter/parser_creator.o"
	@echo "... mime_filter/parser_creator.i"
	@echo "... mime_filter/parser_creator.s"
	@echo "... mime_filter/parser_utils.o"
	@echo "... mime_filter/parser_utils.i"
	@echo "... mime_filter/parser_utils.s"
	@echo "... mime_filter/stack.o"
	@echo "... mime_filter/stack.i"
	@echo "... mime_filter/stack.s"
	@echo "... proxy_pop3/admin.o"
	@echo "... proxy_pop3/admin.i"
	@echo "... proxy_pop3/admin.s"
	@echo "... proxy_pop3/admin_actions.o"
	@echo "... proxy_pop3/admin_actions.i"
	@echo "... proxy_pop3/admin_actions.s"
	@echo "... proxy_pop3/admin_deserializer.o"
	@echo "... proxy_pop3/admin_deserializer.i"
	@echo "... proxy_pop3/admin_deserializer.s"
	@echo "... proxy_pop3/admin_parse_response.o"
	@echo "... proxy_pop3/admin_parse_response.i"
	@echo "... proxy_pop3/admin_parse_response.s"
	@echo "... proxy_pop3/admin_parser_request.o"
	@echo "... proxy_pop3/admin_parser_request.i"
	@echo "... proxy_pop3/admin_parser_request.s"
	@echo "... proxy_pop3/admin_serializer.o"
	@echo "... proxy_pop3/admin_serializer.i"
	@echo "... proxy_pop3/admin_serializer.s"
	@echo "... proxy_pop3/buffer.o"
	@echo "... proxy_pop3/buffer.i"
	@echo "... proxy_pop3/buffer.s"
	@echo "... proxy_pop3/client_parser_request.o"
	@echo "... proxy_pop3/client_parser_request.i"
	@echo "... proxy_pop3/client_parser_request.s"
	@echo "... proxy_pop3/client_parser_response.o"
	@echo "... proxy_pop3/client_parser_response.i"
	@echo "... proxy_pop3/client_parser_response.s"
	@echo "... proxy_pop3/client_request.o"
	@echo "... proxy_pop3/client_request.i"
	@echo "... proxy_pop3/client_request.s"
	@echo "... proxy_pop3/client_request_utils.o"
	@echo "... proxy_pop3/client_request_utils.i"
	@echo "... proxy_pop3/client_request_utils.s"
	@echo "... proxy_pop3/client_response.o"
	@echo "... proxy_pop3/client_response.i"
	@echo "... proxy_pop3/client_response.s"
	@echo "... proxy_pop3/client_response_utils.o"
	@echo "... proxy_pop3/client_response_utils.i"
	@echo "... proxy_pop3/client_response_utils.s"
	@echo "... proxy_pop3/external_transformation.o"
	@echo "... proxy_pop3/external_transformation.i"
	@echo "... proxy_pop3/external_transformation.s"
	@echo "... proxy_pop3/filter_list.o"
	@echo "... proxy_pop3/filter_list.i"
	@echo "... proxy_pop3/filter_list.s"
	@echo "... proxy_pop3/input_parser.o"
	@echo "... proxy_pop3/input_parser.i"
	@echo "... proxy_pop3/input_parser.s"
	@echo "... proxy_pop3/logs.o"
	@echo "... proxy_pop3/logs.i"
	@echo "... proxy_pop3/logs.s"
	@echo "... proxy_pop3/main.o"
	@echo "... proxy_pop3/main.i"
	@echo "... proxy_pop3/main.s"
	@echo "... proxy_pop3/metrics.o"
	@echo "... proxy_pop3/metrics.i"
	@echo "... proxy_pop3/metrics.s"
	@echo "... proxy_pop3/msg_queue.o"
	@echo "... proxy_pop3/msg_queue.i"
	@echo "... proxy_pop3/msg_queue.s"
	@echo "... proxy_pop3/parser.o"
	@echo "... proxy_pop3/parser.i"
	@echo "... proxy_pop3/parser.s"
	@echo "... proxy_pop3/pipelining.o"
	@echo "... proxy_pop3/pipelining.i"
	@echo "... proxy_pop3/pipelining.s"
	@echo "... proxy_pop3/pop3_handler.o"
	@echo "... proxy_pop3/pop3_handler.i"
	@echo "... proxy_pop3/pop3_handler.s"
	@echo "... proxy_pop3/pop3_multi.o"
	@echo "... proxy_pop3/pop3_multi.i"
	@echo "... proxy_pop3/pop3_multi.s"
	@echo "... proxy_pop3/pop3_session.o"
	@echo "... proxy_pop3/pop3_session.i"
	@echo "... proxy_pop3/pop3_session.s"
	@echo "... proxy_pop3/pop3nio.o"
	@echo "... proxy_pop3/pop3nio.i"
	@echo "... proxy_pop3/pop3nio.s"
	@echo "... proxy_pop3/selector.o"
	@echo "... proxy_pop3/selector.i"
	@echo "... proxy_pop3/selector.s"
	@echo "... proxy_pop3/stm.o"
	@echo "... proxy_pop3/stm.i"
	@echo "... proxy_pop3/stm.s"
	@echo "... proxy_pop3/utils.o"
	@echo "... proxy_pop3/utils.i"
	@echo "... proxy_pop3/utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

